### PR TITLE
* Ability to update template files. To use for duplication.

### PR DESCRIPTION
**Pull request by agibralter**
Could we add this method?

### CODE REVIEW

**Comment by jyoung488** [comment]
@agibralter thank you! this method is already available and updated as of [v.3.6.3](https://github.com/HelloFax/hellosign-ruby-sdk/releases/tag/v3.6.3) - does this method work for you? I noticed it's slightly different but the original method does process the client_id.

If not, would you be able to pull the latest version and push any changes? Thank you!

**Comment by agibralter** [comment]
@jyoung488 oops, I'm so sorry—I hadn't noticed! I'll test out the version of your method. Thank you!

**Comment by agibralter** [comment]
Hi @jyoung488, do you know why some methods such as [create_embedded_template_draft](https://github.com/grnhse/hellosign-ruby-sdk/blob/2f5531de806f07538a3e9d463948cfe9af8a8182/lib/hello_sign/api/template.rb#L155) has the code `opts[:client_id] ||= self.client_id`, but nothing else seems to?

I'm trying to figure out if there's a legitimate reason for our version to do that (another engineer implemented it, and I'm not sure of the reason).

**Comment by jyoung488** [comment]
@agibralter This is because only the [Create Embedded Template Draft](https://app.hellosign.com/api/reference#create_embedded_template_draft) endpoint requires the client_id, since it's associated with an API App. The rest of the Template endpoints aren't API App-specific so that parameter isn't allowed or is optional. Let me know if this makes sense! I'm also happy to clarify if you write into apisupport@hellosign.com. Thanks again for your help!

**Comment by agibralter** [comment]
Thank you!!

**Pull request closed without merging**
