### PR TITLE
Support get_url option for signature_request_file

### PR DESCRIPTION
**Pull request by cselmer**

### CODE REVIEW

**Comment by dudo** [comment]
Hello! I believe this is a PR for my company. I noticed a bug with multi signers. Any status update on this being merged?

**Comment by cselmer** [comment]
@dudo - are you saying this pull request introduces a bug with multi signers? Or that there's a bug with multi signers and this fixes it?

**Comment by dudo** [comment]
I believe it fixes a bug...

**Comment by alexmac05** [comment]
@dudo Would you be able to document your issue regarding multi-signers on another thread? Perhaps an issue? We would be interested in learning more details about what you are discussing. I do not believe it is related to this pull request through. 

This pull request is in regards to adding the get_url param to GET /signature_request/files/:signature_request_id

If you could document your issue above under issues, we could look into it. Thanks!
You could create a new issue using this link:
https://github.com/HelloFax/hellosign-ruby-sdk/issues/new

**Comment by zjwhitehead** [comment]
+1
What's the timeline for getting this merged in and the gem version updated?

**Comment by timrwilliams** [comment]
@angelafield Any reason why this wasn't  included in the last version bump? It seems to be a straight forward fix and has specs in place.

**Comment by cselmer** [comment]
@angelafield Thanks!

**Pull request merged**
