### PR TITLE
readme and styles updated

### PR DESCRIPTION
**Pull request by torbjon**
fixed broken link

### CODE REVIEW

**Comment by asolberg** [comment]
We haven't had a chance to review this yet, but we will soon.

**Comment by asolberg** [comment]
Ok - the formatting changes all look fine, though I did post a couple of questions in the commits I'd like you to respond to before I can merge this.

**Comment by asolberg** [comment]
This has been merged, thanks for your contribution!

**Comment by torbjon** [comment]
awesome ;)

**Pull request merged**
